openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0
  description: A sample API to demonstrate OpenAPI with a POST endpoint using a defined schema
servers:
  - url: "http://localhost:8080"
paths:
  /example:
    post:
      summary: Create an example resource
      requestBody:
        description: Example resource to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Example'
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
        '400':
          description: Bad request
  /example2:
    post:
      summary: Create an example2 resource
      requestBody:
        description: Example2 resource to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Example2'
      responses:
        '201':
          description: Resource created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
        '400':
          description: Bad request
components:
  schemas:
    Example:
      type: object
      properties:
        name:
          type: string
          example: Example Name
        description:
          type: string
          example: This is an example description.
        value:
          type: number
          example: 42.0
      required:
        - name
        - value
    Example2:
      type: object
      allOf:
        - $ref: "#/components/schemas/Base"
        - type: object
          properties:
            name:
              type: string
              example: Example Name
            description:
              type: string
              example: This is an example description.
            value:
              type: number
              example: 42.0
      required:
        - name
        - value
    Base:
      type: object
      properties:
        base:
          type: string
    ExampleResponse:
      type: object
      properties:
        id:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        name:
          type: string
          example: Example Name
        description:
          type: string
          example: This is an example description.
        value:
          type: number
          example: 42.0
        createdAt:
          type: string
          format: date-time
          example: "2023-04-05T14:30:00Z"
